/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.DAOEstudiante;
import javax.swing.JOptionPane;
import modelos.Estudiante;

/**
 *
 * @author Vane
 */
public class CrearE extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearE
     */
    public CrearE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCabeceraCrearE = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelCuerpoCrearE = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNomEstudiante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cajaNota1 = new javax.swing.JTextField();
        cajaNota2 = new javax.swing.JTextField();
        cajaNota3 = new javax.swing.JTextField();
        PanelBotonesCrearE = new javax.swing.JPanel();
        btnCrearE = new javax.swing.JButton();
        btnCancelarE = new javax.swing.JButton();

        setClosable(true);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setPreferredSize(new java.awt.Dimension(463, 326));

        PanelCabeceraCrearE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("CREACION ESTUDIANTE");

        javax.swing.GroupLayout PanelCabeceraCrearELayout = new javax.swing.GroupLayout(PanelCabeceraCrearE);
        PanelCabeceraCrearE.setLayout(PanelCabeceraCrearELayout);
        PanelCabeceraCrearELayout.setHorizontalGroup(
            PanelCabeceraCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCabeceraCrearELayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelCabeceraCrearELayout.setVerticalGroup(
            PanelCabeceraCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCabeceraCrearELayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelCuerpoCrearE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Nombre estudiante:");

        cajaNomEstudiante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cajaNomEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaNomEstudianteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nota 1:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nota 2:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Nota 3:");

        cajaNota1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cajaNota2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        cajaNota3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout PanelCuerpoCrearELayout = new javax.swing.GroupLayout(PanelCuerpoCrearE);
        PanelCuerpoCrearE.setLayout(PanelCuerpoCrearELayout);
        PanelCuerpoCrearELayout.setHorizontalGroup(
            PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaNomEstudiante))
                    .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                        .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cajaNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaNota2)
                                    .addComponent(cajaNota3))))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelCuerpoCrearELayout.setVerticalGroup(
            PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuerpoCrearELayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cajaNomEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cajaNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cajaNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelCuerpoCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cajaNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelBotonesCrearE.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearE.setText("CREAR");
        btnCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEActionPerformed(evt);
            }
        });

        btnCancelarE.setText("CANCELAR");
        btnCancelarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesCrearELayout = new javax.swing.GroupLayout(PanelBotonesCrearE);
        PanelBotonesCrearE.setLayout(PanelBotonesCrearELayout);
        PanelBotonesCrearELayout.setHorizontalGroup(
            PanelBotonesCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesCrearELayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnCrearE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBotonesCrearELayout.setVerticalGroup(
            PanelBotonesCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesCrearELayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesCrearELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearE)
                    .addComponent(btnCancelarE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelCuerpoCrearE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelBotonesCrearE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelCabeceraCrearE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCabeceraCrearE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelCuerpoCrearE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelBotonesCrearE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarEActionPerformed

    private void btnCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEActionPerformed
        String cajaNombreEstudiante = cajaNomEstudiante.getText();
        
        if (cajaNombreEstudiante.isEmpty()){
            JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Debe escribir el nombre del estudiante.");
        } else {
            DAOEstudiante objDaoEstudiante = new DAOEstudiante();
            Estudiante objEstudiante = new Estudiante();
                                
            objEstudiante.setNombreEstudiante(cajaNombreEstudiante);
            
            if(objDaoEstudiante.agregar(objEstudiante)){
                cajaNomEstudiante.setText("");
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "No se puede crear el registro.");
            }
            
            cajaNomEstudiante.requestFocus();
        }
        
        int Nota1, Nota2, Nota3, NotaFinal;
        
        
        Nota1 = Integer.getInteger(cajaNota1.getText());
        Nota2 = Integer.getInteger(cajaNota2.getText());
        Nota3 = Integer.getInteger(cajaNota3.getText());
        
        
        if (Nota1<0){
            JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Debe escribir la nota 1 del estudiante.");
        } else {
            DAOEstudiante objDaoEstudiante = new DAOEstudiante();
            Estudiante objEstudiante = new Estudiante();
            
            objEstudiante.setNota1(Nota1);
            
            if(objDaoEstudiante.agregar(objEstudiante)){
                cajaNota1.setText("");
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "No se puede crear el registro.");
            }
        }
        
        if (Nota2<0){
            JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Debe escribir la nota 2 del estudiante.");
        } else {
            DAOEstudiante objDaoEstudiante = new DAOEstudiante();
            Estudiante objEstudiante = new Estudiante();
            
            objEstudiante.setNota2(Nota2);
            
            if(objDaoEstudiante.agregar(objEstudiante)){
                cajaNota2.setText("");
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "No se puede crear el registro.");
            }
        }
        if (Nota3<0){
            JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Debe escribir la nota 3 del estudiante.");
        } else {
            DAOEstudiante objDaoEstudiante = new DAOEstudiante();
            Estudiante objEstudiante = new Estudiante();
            
            objEstudiante.setNota3(Nota3);
            
            if(objDaoEstudiante.agregar(objEstudiante)){
                cajaNota3.setText("");
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "Registro agregado correctamente.");
            }else{
                JOptionPane.showMessageDialog(PanelCuerpoCrearE, "No se puede crear el registro.");
            }
        }
        
        
        
    }//GEN-LAST:event_btnCrearEActionPerformed

    private void cajaNomEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaNomEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaNomEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotonesCrearE;
    private javax.swing.JPanel PanelCabeceraCrearE;
    private javax.swing.JPanel PanelCuerpoCrearE;
    private javax.swing.JButton btnCancelarE;
    private javax.swing.JButton btnCrearE;
    private javax.swing.JTextField cajaNomEstudiante;
    private javax.swing.JTextField cajaNota1;
    private javax.swing.JTextField cajaNota2;
    private javax.swing.JTextField cajaNota3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
