package formularios;

import javax.swing.JInternalFrame;

/**
 *
 * @author Vane
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal2
     */
    public Principal2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        tablero = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuPerfiles = new javax.swing.JMenu();
        jMenuItemCrearE = new javax.swing.JMenuItem();
        jMenuItemListarE = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablero.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout tableroLayout = new javax.swing.GroupLayout(tablero);
        tablero.setLayout(tableroLayout);
        tableroLayout.setHorizontalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        tableroLayout.setVerticalGroup(
            tableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        jMenuArchivo.setText("Archivo");

        jMenuItemAcercaDe.setText("Acerca De");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemAcercaDe);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuPerfiles.setText("Perfiles");

        jMenuItemCrearE.setText("Crear Estudiante");
        jMenuItemCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearEActionPerformed(evt);
            }
        });
        jMenuPerfiles.add(jMenuItemCrearE);

        jMenuItemListarE.setText("Listar Estudiante");
        jMenuItemListarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarEActionPerformed(evt);
            }
        });
        jMenuPerfiles.add(jMenuItemListarE);

        jMenuBar1.add(jMenuPerfiles);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearEActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        CrearE ventanaPerfilCrear;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaPerfilCrear = new CrearE();
        //**********************************************************************
        agregarVentanaPanel(ventanaPerfilCrear);
        ventanaPerfilCrear.show();
        //**********************************************************************
    }//GEN-LAST:event_jMenuItemCrearEActionPerformed

    private void jMenuItemListarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarEActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        PerfilListar ventanaPerfilListar;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaPerfilListar = new PerfilListar();
        //**********************************************************************
        agregarVentanaPanel(ventanaPerfilListar);
        ventanaPerfilListar.show();
        //**********************************************************************
    }//GEN-LAST:event_jMenuItemListarEActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        //**********************************************************************
        //definicion de variables
        //**********************************************************************
        AcercaDe ventanaAcercaDe;
        //**********************************************************************
        //**********************************************************************
        //creacion de objetos
        //**********************************************************************
        ventanaAcercaDe = new AcercaDe();
        //**********************************************************************
        agregarVentanaPanel(ventanaAcercaDe);
        ventanaAcercaDe.show();
        //**********************************************************************
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void agregarVentanaPanel(JInternalFrame ventana){
        if(tablero.getComponentCount() > 0){
            tablero.removeAll();
        }
        tablero.add(ventana);
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCrearE;
    private javax.swing.JMenuItem jMenuItemListarE;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuPerfiles;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables
}
